package app.farvater.core.catalog

object RuApps {
    val packages: Set<String> = setOf(
        "ru.sberbankmobile",
        "com.idamob.tinkoff.android",
        "ru.vtb24.mobilebanking.android",
        "ru.alfabank.mobile.android",
        "ru.gazprombank.android.mobilebank.app",
        "ru.ozon.fintech.finance",
        "ru.nspk.mirpay",
        "ru.rostel",
        "ru.ozon.app.android",
        "com.wildberries.ru",
        "ru.megamarket.marketplace",
        "com.avito.android",
        "ru.sbcs.store",
        "ru.instamart",
        "ru.beru.android",
        "ru.foodfox.client",
        "ru.yandex.yandexmaps",
        "ru.yandex.yandexnavi",
        "ru.yandex.taxi",
        "ru.yandex.music",
        "ru.kinopoisk",
        "com.vkontakte.android",
        "com.vk.vkvideo",
        "com.uma.musicvk",
        "ru.ok.android",
        "ru.mail.mailapp",
        "ru.oneme.app",
        "ru.zen.android",
        "ru.vk.store",
        "ru.rutube.app",
        "ru.dublgis.dgismobile",
        "ru.mts.mymts",
        "ru.megafon.mlk",
        "ru.beeline.services",
        "ru.tele2.mytele2",
    )
}
